name: Austin Wang
markdown: kramdown
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"
encoding: utf-8

collections:
  projects:
    output: true
    permalink: /portfolio/:path/
  years:
    output: true
  tags:
    
